version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ticket-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
  redis:
    image: redis:7-alpine
    container_name: ticket-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
  postgres:
    image: 'postgres:latest'
    container_name: postgres-ticket-app
    environment:
      - 'POSTGRES_DB=ticket_app'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

# docker-compose up -d --build --scale app={pocet instanci}
# prikaz by mel buildnout celej backend a pak spustit vsechny sluzby v compose vcetne javy
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ticket_app
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  nginx:
    image: nginx:latest
    container_name: ticket-load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  postgres_data:
    driver: local